


/**********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0
 *      
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *		此为实体基类，只需重新生成不许修改
 *      Create date: 2015-09-18 10:51:10
 *  </auto-generated>
 * ********************************************************************************************************************/

/**********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/



using System;
using HyBy.FrameWork.DAService;

namespace HyBy.Trading.BusinessEntity
{

    public class CM_UserListEntityBase : Entity
    {

        /// <summary>
        /// 
        /// </summary>		
        public Int64 UserID { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? DiquID { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public string UserKahao { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public string Pwd { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? BuMen { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? ZhiWu { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? JiBie { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public string UserName { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public decimal? BaseGongZi { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public decimal? ShiGongZi { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public decimal? ZhengGongZi { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? ZhuangTai { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public Int64? UserType { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public string CreatorID { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 
        /// </summary>		
        public string Memo { get; set; }


    }
}


