


/**********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0
 *      
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *		此为实体基类，只需重新生成不许修改
 *      Create date: 2015-09-17 17:33:27
 *  </auto-generated>
 * ********************************************************************************************************************/

/**********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/



using System;
using System.Collections.Generic;

using HyBy.Trading.BusinessEntity;

namespace HyBy.Trading.BusinessInterface
{	

	public interface ICM_UserListServiceBase : IBusinessService
    {
                 
        CM_UserListEntity GetCM_UserListEntityByID(string entityID);

        CM_UserListEntity GetCM_UserListEntity(CM_UserListEntity item);

        CM_UserListEntity InsertCM_UserListEntity(CM_UserListEntity item);

        void UpdateCM_UserListEntity(CM_UserListEntity item);

        List<CM_UserListEntity> GetCM_UserListCollection(System.Collections.Generic.Dictionary<string, object> args);
        
    }
}


