

 
/* *********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/
/* *********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0  
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *  </auto-generated>
 *  <summary>
 *      Author:		    System
 *      Create date:	2015-09-21 11:38:45
 *      Description:	插入单行数据
 *  </summary>
 * ********************************************************************************************************************/


IF OBJECT_ID( '[dbo].[InsertCM_UserListEntity]', 'P' ) IS NOT NULL
	DROP  PROCEDURE  [dbo].[InsertCM_UserListEntity]
GO

CREATE PROCEDURE [dbo].[InsertCM_UserListEntity]
(
    			 
		@UserID bigint   output     ,			 
		@DiquID bigint     ,			 
		@UserKahao nvarchar     ,			 
		@Pwd nvarchar     ,			 
		@BuMen bigint     ,			 
		@ZhiWu bigint     ,			 
		@JiBie bigint     ,			 
		@UserName nvarchar     ,			 
		@BaseGongZi money     ,			 
		@ShiGongZi money     ,			 
		@ZhengGongZi money     ,			 
		@ZhuangTai bigint     ,			 
		@UserType bigint     ,			 
		@CreatorID nvarchar     ,			 
		@CreateTime datetime     ,			 
		@Memo nvarchar     	 
)
AS   
 begin
	exec p_getMaxID 'CM_UserList','null', @ID output
	Insert into CM_UserList
	 (
	UserID,DiquID,UserKahao,Pwd,BuMen,ZhiWu,JiBie,UserName,BaseGongZi,ShiGongZi,ZhengGongZi,ZhuangTai,UserType,CreatorID,CreateTime,Memo	)
	values
(
				 
		@UserID    ,	    		 
		@DiquID    ,	    		 
		@UserKahao    ,	    		 
		@Pwd    ,	    		 
		@BuMen    ,	    		 
		@ZhiWu    ,	    		 
		@JiBie    ,	    		 
		@UserName    ,	    		 
		@BaseGongZi    ,	    		 
		@ShiGongZi    ,	    		 
		@ZhengGongZi    ,	    		 
		@ZhuangTai    ,	    		 
		@UserType    ,	    		 
		@CreatorID    ,	    		 
		@CreateTime    ,	    		 
		@Memo    	     
	
	)

  
 end


 
　
 

 /* *********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/
/* *********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0  
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *  </auto-generated>
 *  <summary>
 *      Author:		    System
 *      Create date: 2015-09-21 11:38:45
 *      Description:	根据ID更新一行数据
 *  </summary>
 * ********************************************************************************************************************/
　

 
IF OBJECT_ID( '[dbo].[UpdateCM_UserListEntity]', 'P' ) IS NOT NULL
	DROP  PROCEDURE  [dbo].[UpdateCM_UserListEntity]
GO

CREATE PROCEDURE [dbo].[UpdateCM_UserListEntity]
(
			 
		@UserID bigint,			 
		@DiquID bigint,			 
		@UserKahao nvarchar,			 
		@Pwd nvarchar,			 
		@BuMen bigint,			 
		@ZhiWu bigint,			 
		@JiBie bigint,			 
		@UserName nvarchar,			 
		@BaseGongZi money,			 
		@ShiGongZi money,			 
		@ZhengGongZi money,			 
		@ZhuangTai bigint,			 
		@UserType bigint,			 
		@CreatorID nvarchar,			 
		@CreateTime datetime,			 
		@Memo nvarchar	 
)
AS   
 BEGIN
	UPDATE CM_UserList
	SET
						UserID = @UserID, 
						DiquID = @DiquID, 
						UserKahao = @UserKahao, 
						Pwd = @Pwd, 
						BuMen = @BuMen, 
						ZhiWu = @ZhiWu, 
						JiBie = @JiBie, 
						UserName = @UserName, 
						BaseGongZi = @BaseGongZi, 
						ShiGongZi = @ShiGongZi, 
						ZhengGongZi = @ZhengGongZi, 
						ZhuangTai = @ZhuangTai, 
						UserType = @UserType, 
						CreatorID = @CreatorID, 
						CreateTime = @CreateTime, 
						Memo = @Memo 
		 
	WHERE 
						UserID = @UserID																																																																																												 
 END


  /* *********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/
/* *********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0  
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *  </auto-generated>
 *  <summary>
 *      Author:		    System
 *      Create date: 2015-09-21 11:38:45
 *      Description:	根据主键获取一行数据
 *  </summary>
 * ********************************************************************************************************************/


 
IF OBJECT_ID( '[dbo].[GetCM_UserListEntity]', 'P' ) IS NOT NULL
	DROP  PROCEDURE  [dbo].[GetCM_UserListEntity]
GO

CREATE PROCEDURE [dbo].[GetCM_UserListEntity]
(
	@UserID bigint 
)
AS   
 BEGIN
	SELECT  UserID, DiquID, UserKahao, Pwd, BuMen, ZhiWu, JiBie, UserName, BaseGongZi, ShiGongZi, ZhengGongZi, ZhuangTai, UserType, CreatorID, CreateTime, Memo  
	FROM CM_UserList
	
WHERE 
			UserID = @UserID																																														 
 END


  /* *********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/
/* *********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0  
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *  </auto-generated>
 *  <summary>
 *      Author:		    System
 *      Create date: 2015-09-21 11:38:45
 *      Description:	获取所有数据
 *  </summary>
 * ********************************************************************************************************************/


 
IF OBJECT_ID( '[dbo].[GetCM_UserListEntityCollection]', 'P' ) IS NOT NULL
	DROP  PROCEDURE  [dbo].[GetCM_UserListEntityCollection]
GO

CREATE PROCEDURE [dbo].[GetCM_UserListEntityCollection]

AS   
 BEGIN
	SELECT  UserID, DiquID, UserKahao, Pwd, BuMen, ZhiWu, JiBie, UserName, BaseGongZi, ShiGongZi, ZhengGongZi, ZhuangTai, UserType, CreatorID, CreateTime, Memo  
	FROM CM_UserList
	 
 END















