


/**********************************************************************************************************************
 *  <auto-generated>
 *      此代码由T4模板自动生成
 *      运行时版本: 1.0.0.0
 *      
 *      对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
 *		此为实体基类，只需重新生成不许修改
 *      Create date: 2015-09-21 13:37:45
 *  </auto-generated>
 * ********************************************************************************************************************/

/**********************************************************************************************************************
 * 
 *  版权所有：(c)2015， 华跃博弈有限公司
 * 
 * ********************************************************************************************************************/


using System.Collections.Generic;

using HyBy.Trading.BusinessEntity;
using HyBy.FrameWork.DAService;

namespace HyBy.Trading.BusinessImplement
{

    public class CM_UserListDBOBase : DBO
    {
        /// <summary>
        /// Set store procedures parameter
        /// </summary>
        public CM_UserListDBOBase()
        {
            ///Sql Server 查询参数
            SqlDBMapping[SelectDBMappingIndex] = new DBMappingCollection();
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("UserID", "UserID", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("DiquID", "DiquID", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("UserKahao", "UserKahao", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("Pwd", "Pwd", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("BuMen", "BuMen", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("ZhiWu", "ZhiWu", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("JiBie", "JiBie", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("UserName", "UserName", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("BaseGongZi", "BaseGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("ShiGongZi", "ShiGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("ZhengGongZi", "ZhengGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("ZhuangTai", "ZhuangTai", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("UserType", "UserType", System.Data.SqlDbType.BigInt));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("CreatorID", "CreatorID", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("CreateTime", "CreateTime", System.Data.SqlDbType.DateTime));
            SqlDBMapping[SelectDBMappingIndex].Add(new SqlDBMapping("Memo", "Memo", System.Data.SqlDbType.NVarChar));


            ///Sql Server 更新参数
            SqlDBMapping[UpdateDBMappingIndex] = new DBMappingCollection();
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("DiquID", "DiquID", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("UserKahao", "UserKahao", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("Pwd", "Pwd", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("BuMen", "BuMen", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("ZhiWu", "ZhiWu", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("JiBie", "JiBie", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("UserName", "UserName", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("BaseGongZi", "BaseGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("ShiGongZi", "ShiGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("ZhengGongZi", "ZhengGongZi", System.Data.SqlDbType.Money));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("ZhuangTai", "ZhuangTai", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("UserType", "UserType", System.Data.SqlDbType.BigInt));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("CreatorID", "CreatorID", System.Data.SqlDbType.NVarChar));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("CreateTime", "CreateTime", System.Data.SqlDbType.DateTime));
            SqlDBMapping[UpdateDBMappingIndex].Add(new SqlDBMapping("Memo", "Memo", System.Data.SqlDbType.NVarChar));


            ///Sql Server 主键参数
            SqlDBMapping[PKDBMappingIndex] = new DBMappingCollection();
            SqlDBMapping[PKDBMappingIndex].Add(new SqlDBMapping("UserID", "UserID", System.Data.SqlDbType.BigInt));



            ///Common 查询参数
            ///DBMapping[SelectDBMappingIndex] = new DBMappingCollection();
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("UserID","UserID",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("DiquID","DiquID",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("UserKahao","UserKahao",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("Pwd","Pwd",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("BuMen","BuMen",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("ZhiWu","ZhiWu",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("JiBie","JiBie",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("UserName","UserName",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("BaseGongZi","BaseGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("ShiGongZi","ShiGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("ZhengGongZi","ZhengGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("ZhuangTai","ZhuangTai",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("UserType","UserType",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("CreatorID","CreatorID",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("CreateTime","CreateTime",System.Data.SqlDbType.DateTime));
            ///			///DBMapping[SelectDBMappingIndex].Add(new DBMapping("Memo","Memo",System.Data.SqlDbType.NVarChar));
            /// 

            ///Common 更新参数
            /// DBMapping[UpdateDBMappingIndex] = new DBMappingCollection();
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("UserID","UserID",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("DiquID","DiquID",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("UserKahao","UserKahao",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("Pwd","Pwd",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("BuMen","BuMen",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("ZhiWu","ZhiWu",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("JiBie","JiBie",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("UserName","UserName",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("BaseGongZi","BaseGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("ShiGongZi","ShiGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("ZhengGongZi","ZhengGongZi",System.Data.SqlDbType.Money));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("ZhuangTai","ZhuangTai",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("UserType","UserType",System.Data.SqlDbType.BigInt));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("CreatorID","CreatorID",System.Data.SqlDbType.NVarChar));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("CreateTime","CreateTime",System.Data.SqlDbType.DateTime));
            ///			///DBMapping[UpdateDBMappingIndex].Add(new DBMapping("Memo","Memo",System.Data.SqlDbType.NVarChar));
            /// 

            ///Common 主键参数
            ///DBMapping[PKDBMappingIndex] = new DBMappingCollection();
            ///			///			///DBMapping[PKDBMappingIndex].Add(new DBMapping("UserID","UserID",System.Data.SqlDbType.BigInt));
            /// 
            ///			///			///			///			///			///			///			///			///			///			///			///			///			///			///			/// 

        }

        /// <summary>
        /// Get Entity by id.
        /// </summary>
        /// <param name="entityID"></param>
        /// <returns>Entity</returns>
        public virtual CM_UserListEntity GetCM_UserListEntityByID(string entityID)
        {
            CM_UserListEntity item = new CM_UserListEntity();
            item.EntityID = entityID;
            this.GetCM_UserListEntity(item);
            return item;
        }

        /// <summary>
        /// Get Entity by Key
        /// </summary>
        /// <param name="item">Entity</param>
        public virtual void GetCM_UserListEntity(CM_UserListEntity item)
        {
            this.GetByKey("GetCM_UserListEntity", item);
        }

        /// <summary>
        /// Insert Entity by Key
        /// </summary>
        /// <param name="item">Entity</param>
        public virtual void InsertCM_UserListEntity(CM_UserListEntity item)
        {
            this.InsertEntity("InsertCM_UserListEntity", item);
        }

        /// <summary>
        /// Update Entity by Key
        /// </summary>
        /// <param name="item">Entity</param>
        public virtual void UpdateCM_UserListEntity(CM_UserListEntity item)
        {
            this.UpdateByKey("UpdateCM_UserListEntity", item);
        }

        /// <summary>
        /// Get All
        /// </summary>
        /// <param name="args">args</param>
        /// <returns>List</returns>
        public virtual List<CM_UserListEntity> GetCM_UserListCollection(Dictionary<string, object> args)
        {
            CM_UserListEntity item = new CM_UserListEntity();
            return (List<CM_UserListEntity>)this.GetAllBySP("GetCM_UserListCollection", item, args);
        }

    }
}


